name: Install Python tooling
description: "Install python tools"

inputs:
  PythonVersion:
    description: "PythonVersion"
    required: false
    default: 3.10.7
  RequirementFilePath:
    description: "Path to the requirements.txt"
    required: false
    default: "./requirements.txt"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.PythonVersion }}  # Specify your desired Python version
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.RequirementFilePath }}
