# dbt run-operation codegen.create_base_models --args '{"source_name": "raw_data", "tables": ["address","addresstype","billofmaterials","businessentity","businessentityaddress","businessentitycontact","contacttype","countryregion","countryregioncurrency","creditcard","culture","currency","currencyrate","customer","department","document","emailaddress","employee","employeedepartmenthistory","employeepayhistory","illustration","jobcandidate","location","password","person","personcreditcard","personphone","phonenumbertype","product","productcategory","productcosthistory","productdescription","productdocument","productinventory","productlistpricehistory","productmodel","productmodelillustration","productmodelproductdescriptionculture","productphoto","productproductphoto","productreview","productsubcategory","productvendor","purchaseorderdetail","purchaseorderheader","salesorderdetail","salesorderheader","salesorderheadersalesreason","salesperson","salespersonquotahistory","salesreason","salestaxrate","salesterritory","salesterritoryhistory","scrapreason","shift","shipmethod","shoppingcartitem","specialoffer","specialofferproduct","stateprovince","store","transactionhistory","transactionhistoryarchive","unitmeasure","vendor","workorder","workorderrouting"]}' > output.txt

source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data address && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data addresstype && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data billofmaterials && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data businessentity && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data businessentityaddress && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data businessentitycontact && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data contacttype && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data countryregion && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data countryregioncurrency && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data creditcard && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data culture && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data currency && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data currencyrate && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data customer && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data department && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data document && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data emailaddress && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data employee && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data employeedepartmenthistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data employeepayhistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data illustration && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data jobcandidate && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data location && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data password && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data person && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data personcreditcard && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data personphone && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data phonenumbertype && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data product && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productcategory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productcosthistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productdescription && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productdocument && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productinventory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productlistpricehistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productmodel && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productmodelillustration && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productmodelproductdescriptionculture && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productphoto && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productproductphoto && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productreview && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productsubcategory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data productvendor && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data purchaseorderdetail && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data purchaseorderheader && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesorderdetail && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesorderheader && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesorderheadersalesreason && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesperson && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salespersonquotahistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesreason && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salestaxrate && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesterritory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data salesterritoryhistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data scrapreason && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data shift && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data shipmethod && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data shoppingcartitem && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data specialoffer && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data specialofferproduct && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data stateprovince && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data store && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data transactionhistory && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data transactionhistoryarchive && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data unitmeasure && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data vendor && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data workorder && 
source dbt_packages/codegen/bash_scripts/base_model_creation.sh raw_data workorderrouting
